### ISSUE TITLE
Enhanced Example e4-receive-timeout

### ISSUE THREAD

**Issue by pwhittin** [suprematic/otplike#19]
I attended the otplike talk at EuroClojure 2017.  I have only just started to understand how I can use otplike.

I have successfully executed Example e4-receive-timeout.  I also added additional output to e4-receive-timeout that helped me better understand the execution sequence of the example.  For your consideration, my modified source code is attached.

[e4_receive_timeout.clj.zip](https://github.com/suprematic/otplike/files/1218793/e4_receive_timeout.clj.zip)

**Comment by sskorokhodov** [comment]
Thank you for the feedback! I'll go through the code tomorrow to decide if it can be used instead of the old example.

**Comment by sskorokhodov** [comment]
I changed your code slightly and pushed it to the branch `issue-19`. Could you please take a look and tell if you are ok with it (commit fde13e4).

**Comment by pwhittin** [comment]
It looks good.

**Comment by sskorokhodov** [comment]
Closed by fde13e4
