### ISSUE TITLE
EuroClojure 2017 Slide 14 Possible Error

### ISSUE THREAD

**Issue by pwhittin** [suprematic/otplike#21]
On slide 14 the following code is displayed:

```clojure
(require '[otplike.gen-server :as gs])

; provide initial state (required!)
(defn init []
   [:ok {}])

; handle sync requests
(defn handle-call [message from state]
  (match message 
    [::add a1 a2]
    [:reply (+ a1 a2) state]))

(defn add [server a1 a2]
  (gs/call server [::add a1 a2]))      

(let [[_ server] (gs/start-ns [])]
  (println "2 + 3 = " (add server 2 3)))
```

In order to get it to compile from a "clean" "lein repl" I had to add the line

```clojure
(require '[clojure.core.match :refer [match]])
```

to the top of the code.

When I did, I received the following error:

```
Exception noproc  otplike.process/self (process.clj:425)
```

I don't know what this means.

**Comment by sskorokhodov** [comment]
I think some statements (like requiring core.match) are omitted on the slides for the sake of brevity.

I'm checking the problem with exception now.

**Comment by pwhittin** [comment]
Do you know of an Erlang example that is fairly complex, but not very complex, that I can "port" to otplike?  I need to understand how to use otplike for my current project, and starting with a well understood Erlang example might be a good approach.  Of course, I would contribute the port to the otplike project when I get it working.

I'd probably need to ask you questions along the way.  Is creating issues the way you would like me to ask questions?

**Comment by sskorokhodov** [comment]
>  Is creating issues the way you would like me to ask questions?

Yes, it would be very nice of you! It also makes it easier for others to find answers to questions that have already been asked.

**Comment by sskorokhodov** [comment]
The problem with the example is here:

```clojure
(gs/start-ns [])
```

`gen-server` can only be started by another process. It must be added to the docstring of `gen-server/start`.
Exception with the reason "noproc" means that caller is supposed to be a process.

**Comment by sskorokhodov** [comment]
> Do you know of an Erlang example that is fairly complex, but not very complex, that I can "port" to otplike?

I think of examples from the [learnyousomeerlang](http://learnyousomeerlang.com) book. Every chapter has one or more good examples supplementing explanation of a concept. I would started from examples given in [this](http://learnyousomeerlang.com/the-hitchhikers-guide-to-concurrency) chapter. The book is also useful because it guides you step by step through the OTP principles.
