### ISSUE TITLE
Typo In Documentation Of otplike.process/exit

### ISSUE THREAD

**Issue by pwhittin** [suprematic/otplike#22]
In the sentence "Throws when callen not in process context, if pid is not a pid, or reason is nil." the string "callen" should be "caller".

**Comment by sskorokhodov** [comment]
Sorry for the late response. I have a vocation now and almost have no time to reply. I'll be almost free next week and I'm planning to concentrate on this project mostly.

**Comment by sskorokhodov** [comment]
Fixed by 25a9642

**Comment by sskorokhodov** [comment]
Fixed by 25a9642

**Comment by pwhittin** [comment]
Enjoy yourself!
