### ISSUE TITLE
Handling backpressure

### ISSUE THREAD

**Issue by xificurC** [suprematic/otplike#43]
Based on some quick reads on the erlang side a message send is fire-and-forget and there's no easy way to provide backpressure on the message queue. What are some other idioms used to handle this scenario:

Process 1 gets data through the network and sends it to process 2.
Process 2 transforms the data and sends it to process 3.
Process 3 sends the data through the network.

If process 1 goes too fast it will eat up a lot of memory in 2 and 3's queues. I have an application where I have N of jobs that consist of 3 threads and 2 queues for the communication between them. The queues are bounded so the threads attempting to put a message in block, thereby creating the necessary backrpressure.

Is the situation same in otplike, messages are fire-and-forget and the queues are always unbounded?

Is there a a "design pattern" used for this? E.g. Process 3 sending messages "ok give me more" to process 1?

**Comment by sskorokhodov** [comment]
Backpressure is on the developer.

Usually, one can use `gen-server/call` to make the caller wait until the response is ready. gen-server, on the other hand, should control the number of parallel requests (if any). As Erlang, `otplike` allows sending the response at any moment after a request has arrived (by saving the `from` argument of the `handle-call` callback).

**Comment by xificurC** [comment]
Makes sense, thanks
